// init.zig — devswarm init subcommand
//
// Probes the current environment (CLIs, tools, git) and writes
// .devswarm/config.toml with sensible defaults and inline comments.

const std = @import("std");
const detect = @import("runtime/detect.zig");
const cascade = @import("runtime/cascade.zig");
const gh = @import("gh.zig");

pub const CONFIG_DIR  = ".devswarm";
pub const CONFIG_PATH = ".devswarm/config.toml";

/// Run devswarm init.  Returns 0 on success, 1 on error.
pub fn run(alloc: std.mem.Allocator, force: bool) u8 {
    const stdout = std.fs.File.stdout();
    const stderr = std.fs.File.stderr();

    // Check for existing config
    const exists = blk: {
        std.fs.cwd().access(CONFIG_PATH, .{}) catch break :blk false;
        break :blk true;
    };
    if (exists and !force) {
        stderr.writeAll("devswarm: " ++ CONFIG_PATH ++ " already exists. Run with --force to overwrite.\n") catch {};
        return 1;
    }

    stdout.writeAll("DevSwarm init — probing environment...\n") catch {};

    // Detect backends and tool availability
    const backends = detect.probe(alloc);
    const tools    = cascade.probe(alloc);

    const has_claude = backends.claude;
    const has_codex  = backends.codex;
    const has_zig    = tools.has_zigrep;
    const has_rg     = tools.has_rg;
    const has_git    = probeCmd(alloc, "git");
    const has_amp    = probeCmd(alloc, "amp");
    // Choose primary provider
    const primary: []const u8 = if (has_claude)
        "claude"
    else if (has_codex)
        "codex"
    else if (has_amp)
        "amp"
    else
        "auto";

    // Infer tool tier label
    const tool_tier: []const u8 = switch (tools.tier()) {
        .zig_tools => "zig_tools",
        .standard  => "standard",
        .minimal   => "minimal",
    };

    // Print detected environment
    stdout.writeAll("\nDetected:\n") catch {};
    printItem(stdout, "claude", has_claude);
    printItem(stdout, "codex ", has_codex);
    printItem(stdout, "amp   ", has_amp);
    printItem(stdout, "git   ", has_git);
    printItem(stdout, "zigrep", has_zig);
    printItem(stdout, "rg    ", has_rg);
    printStatus(stdout, "tool tier", tool_tier);
    stdout.writeAll("\n") catch {};

    if (!has_claude and !has_codex and !has_amp) {
        stdout.writeAll("  no agent backend found. Install claude, codex, or amp and re-run.\n\n") catch {};
    }

    // Write config directory
    std.fs.cwd().makePath(CONFIG_DIR) catch |err| {
        stderr.writeAll("devswarm: failed to create .devswarm/: ") catch {};
        stderr.writeAll(@errorName(err)) catch {};
        stderr.writeAll("\n") catch {};
        return 1;
    };

    const config = buildConfig(alloc, primary, has_claude, has_codex) catch {
        stderr.writeAll("devswarm: OOM building config\n") catch {};
        return 1;
    };
    defer alloc.free(config);

    std.fs.cwd().writeFile(.{
        .sub_path = CONFIG_PATH,
        .data     = config,
    }) catch |err| {
        stderr.writeAll("devswarm: failed to write config: ") catch {};
        stderr.writeAll(@errorName(err)) catch {};
        stderr.writeAll("\n") catch {};
        return 1;
    };

    stdout.writeAll("Wrote " ++ CONFIG_PATH ++ "\n") catch {};
    stdout.writeAll("\nNext steps:\n") catch {};
    stdout.writeAll("  1. Open .devswarm/config.toml and review the settings\n") catch {};
    stdout.writeAll("  2. Add devswarm to your MCP config (Claude Code / Cursor / Codex)\n") catch {};
    stdout.writeAll("  3. Ask your AI: run_swarm with prompt=\"<your task>\"\n") catch {};
    return 0;
}

fn probeCmd(alloc: std.mem.Allocator, cmd: []const u8) bool {
    const r = gh.run(alloc, &.{ cmd, "--version" }) catch return false;
    r.deinit(alloc);
    return true;
}

fn printItem(file: std.fs.File, label: []const u8, found: bool) void {
    const mark = if (found) "  ok  " else "  --  ";
    file.writeAll(mark) catch {};
    file.writeAll(label) catch {};
    file.writeAll(if (found) "\n" else " (not found)\n") catch {};
}

fn printStatus(file: std.fs.File, label: []const u8, value: []const u8) void {
    file.writeAll("  >>  ") catch {};
    file.writeAll(label) catch {};
    file.writeAll(": ") catch {};
    file.writeAll(value) catch {};
    file.writeAll("\n") catch {};
}

fn buildConfig(
    alloc: std.mem.Allocator,
    primary: []const u8,
    has_claude: bool,
    has_codex: bool,
) ![]u8 {
    var buf: std.ArrayList(u8) = .empty;
    errdefer buf.deinit(alloc);

    try buf.appendSlice(alloc,
        "# DevSwarm configuration\n" ++
        "# Generated by: devswarm init\n" ++
        "# Re-generate: devswarm init --force\n" ++
        "#\n" ++
        "# Safe to commit to git (no secrets, no API keys).\n" ++
        "# Per-repo (.devswarm/config.toml) overrides global (~/.config/devswarm/config.toml).\n"
    );

    {
        const chunk = try std.fmt.allocPrint(alloc,
            "\n" ++
            "[provider]\n" ++
            "# Primary agent backend: claude | codex | amp | auto\n" ++
            "# \"auto\" picks whichever is available (claude preferred).\n" ++
            "primary = \"{s}\"\n",
            .{primary},
        );
        defer alloc.free(chunk);
        try buf.appendSlice(alloc, chunk);
    }

    if (has_claude) {
        try buf.appendSlice(alloc,
            "\n" ++
            "# Claude subscription tier: free | pro | max5 | max20 | api\n" ++
            "# DevSwarm uses this to set conservative rate-limit budgets.\n" ++
            "claude_tier = \"pro\"\n" ++
            "\n" ++
            "# Default model for Claude (haiku | sonnet | opus | full model ID)\n" ++
            "claude_default = \"sonnet\"\n"
        );
    }

    if (has_codex) {
        try buf.appendSlice(alloc,
            "\n" ++
            "# Codex subscription tier: none | plus | pro | api\n" ++
            "codex_tier = \"pro\"\n" ++
            "\n" ++
            "# Default model for Codex backend\n" ++
            "codex_default = \"codex-mini-latest\"\n"
        );
    }

    try buf.appendSlice(alloc,
        "\n" ++
        "[provider.quota]\n" ++
        "# Conservative request budgets per rolling hour window (0 = disabled).\n" ++
        "claude_limit    = 900\n" ++
        "codex_limit     = 1500\n" ++
        "warn_at_percent = 80\n" ++
        "\n" ++
        "[agents]\n" ++
        "# Maximum parallel worker threads in a swarm run.\n" ++
        "max_threads = 8\n" ++
        "# Maximum swarm nesting depth (1 = flat, no sub-swarms).\n" ++
        "max_depth   = 1\n" ++
        "\n" ++
        "# Per-role overrides — uncomment and adjust as needed.\n" ++
        "# [agents.finder]\n" ++
        "# model   = \"haiku\"\n" ++
        "# sandbox = \"read-only\"\n" ++
        "#\n" ++
        "# [agents.fixer]\n" ++
        "# model   = \"sonnet\"\n" ++
        "# sandbox = \"write\"\n" ++
        "#\n" ++
        "# [agents.reviewer]\n" ++
        "# model   = \"opus\"\n" ++
        "# sandbox = \"read-only\"\n"
    );

    return buf.toOwnedSlice(alloc);
}
